imgstorage: check before unmapping block device device
sometimes when unmapping the a volume the VM is still holding
the block device by the time imgstorage tries to unmap it and
it gets this error;

Error: Error detaching iSCSI target from compute node: Error executing dmsetup: device-mapper: remove ioctl on vm-rocks-153-1-vol-snap failed: Device or resource busy

To avoid this problem it now performs a check to verify the device
is free before destroing it

TODO: it should re-queue the request instead of sleeping